var routeList = {'1': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '摩星嶺',
'dest': '跑馬地 (上)'},
'1M': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '會展站',
'dest': '跑馬地／黃泥涌峽'},
'1P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '黃泥涌道 (樂活道)',
'dest': '中環'},
'2': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '嘉亨灣',
'dest': '中環 (港澳碼頭)'},
'2A': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '耀東邨',
'dest': '會展站'},
'2X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '嘉亨灣',
'dest': '會展站'},
'3A': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '中環 (天星碼頭)',
'dest': '摩星嶺'},
'4': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '黃竹坑／華富 (南)',
'dest': '中環'},
'4X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '華富 (南)',
'dest': '中環 (交易廣場)'},
'5B': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '堅尼地城',
'dest': '銅鑼灣／香港大球場'},
'5X': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '堅尼地城',
'dest': '銅鑼灣 (威非路道)'},
'6': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '中環 (交易廣場)',
'dest': '赤柱市場'},
'6A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '中環 (交易廣場)',
'dest': '赤柱炮台 (閘口)'},
'6X': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '中環 (交易廣場)',
'dest': '赤柱市場'},
'7': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '石排灣',
'dest': '中環碼頭'},
'8': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '杏花邨',
'dest': '會展站'},
'8H': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '東華東院'},
'8P': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '會展站'},
'8S': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '跑馬地馬場',
'dest': '小西灣 (藍灣半島)'},
'8X': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '跑馬地 (上)'},
'9': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '筲箕灣',
'dest': '石澳'},
'9C': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'o',
'orig': '筲箕灣',
'dest': '歌連臣角'},
'10': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '堅尼地城',
'dest': '北角碼頭'},
'11': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '中環碼頭',
'dest': '渣甸山'},
'12': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '中環3號碼頭',
'dest': '羅便臣道／柏道'},
'12A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '金鐘 (添馬街)',
'dest': '麥當勞道'},
'12M': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '金鐘 (添馬街)',
'dest': '柏道'},
'13': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '金鐘 (添馬街)',
'dest': '旭龢道 (半山區)'},
'14': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '嘉亨灣',
'dest': '赤柱炮台 (閘口)／馬坑'},
'15': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '中環',
'dest': '山頂'},
'15B': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '灣仔 (會展新翼)',
'dest': '山頂'},
'15C': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '中環 (天星碼頭)',
'dest': '花園道 (山頂纜車總站)'},
'18': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '北角 (健康中街)',
'dest': '堅尼地城 (卑路乍灣)／上環'},
'18P': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '堅尼地城 (卑路乍灣)',
'dest': '北角 (健康中街)'},
'18X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '筲箕灣',
'dest': '堅尼地城 (卑路乍灣)'},
'19P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '筲箕灣',
'dest': '跑馬地 (上)'},
'20': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '啟德 (沐安街)',
'dest': '大角咀 (維港灣)'},
'20A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '高鐵西九龍站 (經:旺角)',
'dest': '啟德 (經:九龍城)'},
'20R': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '香港體育館',
'dest': '啟德 (沐安街)'},
'22': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '啟德郵輪碼頭',
'dest': '九龍塘 (又一城)'},
'22M': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '啟德郵輪碼頭',
'dest': '土瓜灣'},
'22X': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '維港1號',
'dest': '啟德站'},
'23': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '北角碼頭',
'dest': '蒲飛路'},
'23B': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '寶馬山',
'dest': '柏道／羅便臣道'},
'23X': {'company': 'NWFB',
'theme': '#0080FF',
'mode': 'o',
'orig': '蒲飛路',
'dest': '西灣河'},
'25': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '中環 (3 號碼頭)',
'dest': '寶馬山'},
'25A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '會展站',
'dest': '寶馬山'},
'26': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '勵德邨',
'dest': '荷李活道'},
'27': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '北角碼頭',
'dest': '寶馬山'},
'30X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '數碼港',
'dest': '金鐘(東)'},
'33X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'o',
'orig': '數碼港',
'dest': '西灣河'},
'37A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '置富花園',
'dest': '中環'},
'37B': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '置富花園',
'dest': '金鐘'},
'37X': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '置富花園',
'dest': '金鐘'},
'38': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '置富花園',
'dest': '北角碼頭'},
'40': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '華富 (北)',
'dest': '會展站'},
'40M': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '華富 (北)',
'dest': '會展站'},
'40P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '華富 (北)',
'dest': '羅便臣道'},
'41A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '華富 (中)',
'dest': '北角碼頭'},
'42': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '華富 (南)',
'dest': '北角碼頭'},
'42C': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '數碼港',
'dest': '北角碼頭'},
'43M': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '田灣',
'dest': '石塘咀'},
'47P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '堅尼地城 (卑路乍灣)',
'dest': '黃竹坑'},
'48': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '深灣／海洋公園',
'dest': '華富 (北)'},
'49X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'o',
'orig': '小西灣 (藍灣半島)',
'dest': '數碼港'},
'50': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '屯門 (菁田及和田)',
'dest': '尖沙咀 (九龍站)'},
'50M': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '和田邨',
'dest': '屯門站'},
'55': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '屯門 (菁田及和田)',
'dest': '觀塘碼頭'},
'56': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '屯門 (菁田及和田)',
'dest': '上水 (天平邨)'},
'56A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '屯門 (菁田及和田)',
'dest': '粉嶺皇后山 (經:上水站)'},
'61R': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '沙田第一城',
'dest': '藍田站'},
'63': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '北角碼頭',
'dest': '赤柱市場'},
'65': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '北角碼頭',
'dest': '赤柱市場'},
'66': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '中環 (交易廣場)',
'dest': '赤柱廣場 (馬坑)'},
'70': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '華貴 (經:香港仔)',
'dest': '中環 (交易廣場)'},
'70P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '石排灣 (經:香港仔)',
'dest': '中環 (交易廣場)'},
'71': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '黃竹坑',
'dest': '中環 (林士街)'},
'71P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '深灣',
'dest': '中環碼頭'},
'72': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '華貴邨',
'dest': '銅鑼灣 (摩頓台)'},
'72A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '深灣',
'dest': '銅鑼灣 (摩頓台)'},
'73': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '數碼港／華富 (北)',
'dest': '赤柱市場'},
'73P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '深灣',
'dest': '數碼港'},
'75': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '深灣',
'dest': '中環 (交易廣場)'},
'76': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '黃竹坑站／石排灣',
'dest': '銅鑼灣 (邊寧頓街)'},
'77': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '田灣',
'dest': '筲箕灣'},
'77A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '筲箕灣',
'dest': '田灣'},
'77X': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '華貴邨',
'dest': '西灣河'},
'78': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '黃竹坑',
'dest': '華貴邨'},
'78X': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '粉嶺皇后山',
'dest': '啟德 (經：觀塘)'},
'79X': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '粉嶺皇后山',
'dest': '長沙灣(西) (經：旺角)'},
'81': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '興華邨',
'dest': '勵德邨'},
'81A': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '興華邨',
'dest': '勵德邨'},
'82': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '北角碼頭'},
'82S': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '耀東 (惠亨街)'},
'82X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '鰂魚涌'},
'85': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '寶馬山／北角'},
'85A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '筲箕灣',
'dest': '寶馬山'},
'85P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '寶馬山'},
'88R': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '沙田第一城',
'dest': '中環'},
'88X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '堅尼地城 (卑路乍灣)'},
'90': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '鴨脷洲邨',
'dest': '中環 (交易廣場)'},
'90B': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '海怡半島',
'dest': '金鐘 (東)'},
'90C': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '鴨脷洲大街',
'dest': '中環 (怡和大廈)'},
'91': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '鴨脷洲邨',
'dest': '中環碼頭'},
'91A': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '鴨脷洲邨',
'dest': '華富 (南)'},
'93': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'o',
'orig': '海怡半島／鴨脷洲邨',
'dest': '羅便臣道'},
'93A': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'o',
'orig': '利東邨',
'dest': '羅便臣道'},
'93C': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '鴨脷洲大街／田灣',
'dest': '堅道'},
'94A': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '華富 (中)',
'dest': '利東邨'},
'95': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '鴨脷洲邨 / 利南道工業區',
'dest': '香港仔 / 石排灣'},
'95C': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '鴨脷洲邨',
'dest': '置富花園'},
'95P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '田灣',
'dest': '鴨脷洲邨'},
'97': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '利東邨',
'dest': '中環 (交易廣場)'},
'98': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '利東邨',
'dest': '香港仔 (成都道)'},
'99': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '海怡半島',
'dest': '筲箕灣'},
'99X': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '海怡半島',
'dest': '西灣河'},
'101': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '堅尼地城',
'dest': '觀塘 (裕民坊)'},
'101R': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '跑馬地馬場',
'dest': '觀塘 (裕民坊)'},
'101X': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '堅尼地城',
'dest': '觀塘 (裕民坊)'},
'102': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '筲箕灣',
'dest': '美孚'},
'102P': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '筲箕灣',
'dest': '美孚'},
'102R': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '跑馬地馬場',
'dest': '美孚'},
'103': {'company': 'CTB',
'theme': '#FB0801',
'mode': 'io',
'orig': '蒲飛路',
'dest': '竹園'},
'104': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '堅尼地城／中環',
'dest': '白田邨'},
'106': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '黃大仙'},
'106A': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '黃大仙',
'dest': '太古 (康怡廣場)'},
'106P': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '黃大仙'},
'107': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '華貴邨',
'dest': '九龍灣'},
'107P': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '紅磡 (海逸豪園)',
'dest': '數碼港'},
'109': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '何文田邨'},
'110': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '筲箕灣',
'dest': '尖沙咀 (麼地道)'},
'111': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '坪石邨'},
'111P': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '彩福邨',
'dest': '中環 (港澳碼頭)'},
'111R': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '灣仔 (會展新翼)',
'dest': '觀塘 (裕民坊)'},
'112': {'company': 'NWFB',
'theme': '#FB0801',
'mode': 'io',
'orig': '北角 (百福道)',
'dest': '蘇屋邨'},
'113': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '堅尼地城 (卑路乍灣)',
'dest': '彩虹'},
'115': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '九龍城碼頭'},
'115P': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '海逸豪園',
'dest': '中環 (港澳碼頭)'},
'116': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '鰂魚涌 (祐民街)',
'dest': '慈雲山 (中)'},
'117': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '跑馬地 (下)',
'dest': '深水埗 (欽州街)'},
'118': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '長沙灣 (深旺道)'},
'118P': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '長沙灣 (深旺道)'},
'148R': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '灣仔 (會展新翼)',
'dest': '青衣(長安)'},
'170': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '華富 (中)',
'dest': '沙田站'},
'171': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '海怡半島',
'dest': '荔枝角'},
'171A': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'o',
'orig': '利東邨',
'dest': '荔枝角'},
'171P': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'o',
'orig': '海怡半島',
'dest': '荔枝角'},
'182': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '沙田 (愉翠苑)'},
'182X': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'o',
'orig': '中環 (港澳碼頭)',
'dest': '沙田 (愉翠苑)'},
'191R': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '灣仔 (會展新翼)',
'dest': '日出康城'},
'260': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '中環 (交易廣場)',
'dest': '赤柱市場'},
'302': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '慈雲山 (北)',
'dest': '上環'},
'302A': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '慈雲山 (北)',
'dest': '北角 (健康村)'},
'307': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '大埔中心',
'dest': '中環碼頭／上環'},
'307A': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'o',
'orig': '大埔頭',
'dest': '上環'},
'307P': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '天后站',
'dest': '大埔 (汀太路)'},
'511': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '大坑徑',
'dest': '中環碼頭'},
'592': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '海怡半島',
'dest': '銅鑼灣 (摩頓台)'},
'595': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '海怡半島',
'dest': '香港仔'},
'601': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '金鐘 (東)',
'dest': '寶達邨'},
'601P': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '寶達邨',
'dest': '上環'},
'606': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '彩雲 (豐盛街)'},
'606A': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '彩雲 (豐盛街)',
'dest': '耀東邨'},
'606X': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '九龍灣'},
'608': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '九龍城 (盛德街)',
'dest': '筲箕灣'},
'608P': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'o',
'orig': '小西灣 (藍灣半島)',
'dest': '九龍城 (盛德街)'},
'619': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '順利邨'},
'619P': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'o',
'orig': '順利邨',
'dest': '中環 (港澳碼頭)'},
'619X': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '順利邨',
'dest': '中環 (港澳碼頭)'},
'621': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '麗港城',
'dest': '中環 (香港站)'},
'629': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '中環 (天星碼頭)',
'dest': '海洋公園 (正門／水上樂園)'},
'629M': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '海洋公園 (水上樂園)',
'dest': '黃竹坑站'},
'641': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '啟德 (啟晴邨)'},
'671': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '鴨脷洲 (利樂街)',
'dest': '鑽石山站'},
'671X': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'o',
'orig': '鴨脷洲 (利樂街)',
'dest': '鑽石山站'},
'678': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '上水',
'dest': '銅鑼灣 (東院道)'},
'679': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '粉嶺皇后山',
'dest': '中環 (香港站)'},
'680': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '金鐘 (東)',
'dest': '馬鞍山 (利安邨)'},
'680B': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '馬鞍山 (富安花園)',
'dest': '金鐘 (東)'},
'680P': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '馬鞍山 (烏溪沙站)',
'dest': '金鐘 (東)'},
'680X': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '馬鞍山 (烏溪沙站)'},
'681': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '中環 (香港站)',
'dest': '馬鞍山市中心'},
'681P': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '馬鞍山 (耀安邨)',
'dest': '上環'},
'682': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '柴灣 (東)',
'dest': '馬鞍山 (烏溪沙站)'},
'682A': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '馬鞍山市中心',
'dest': '柴灣 (東)'},
'682B': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '水泉澳邨',
'dest': '柴灣 (東)'},
'682C': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '沙田第一城',
'dest': '北角'},
'682P': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'o',
'orig': '烏溪沙站',
'dest': '柴灣 (東)'},
'690': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '中環 (交易廣場)',
'dest': '將軍澳 (康盛花園)'},
'690P': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'o',
'orig': '將軍澳 (康盛花園)',
'dest': '中環 (交易廣場)'},
'694': {'company': 'NWFB',
'theme': '#FF0000',
'mode': 'io',
'orig': '小西灣邨',
'dest': '調景嶺站'},
'701': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '海麗邨／南昌站',
'dest': '旺角'},
'701A': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '海盈邨',
'dest': '旺角'},
'701R': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'o',
'orig': '香港體育館',
'dest': '蘇屋'},
'701S': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '海麗邨／南昌站',
'dest': '旺角'},
'702': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '海麗邨／南昌站',
'dest': '九龍塘 (又一城)'},
'702A': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'o',
'orig': '海盈邨',
'dest': '白田邨'},
'702B': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '白田 (北)',
'dest': '海盈邨'},
'702S': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '蘇屋邨',
'dest': '長沙灣 (深盛路)／富昌邨'},
'720': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '嘉亨灣',
'dest': '中環 (港澳碼頭 / 永和街)'},
'720A': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'o',
'orig': '嘉亨灣',
'dest': '金鐘 (海富中心)/ 中環(畢打街)'},
'720P': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '太古城',
'dest': '中環 (永和街)'},
'720X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'o',
'orig': '嘉亨灣',
'dest': '中環(林士街)'},
'722': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '耀東邨',
'dest': '中環碼頭'},
'780': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '柴灣 (東)',
'dest': '中環碼頭'},
'780P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '興華 (經銅鑼灣)',
'dest': '中環碼頭'},
'788': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '中環 (港澳碼頭)'},
'789': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '金鐘 (樂禮街)'},
'790': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '清水灣半島 (經:日出康城)',
'dest': '尖沙咀(麼地道)'},
'792M': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '將軍澳站',
'dest': '西貢'},
'793': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '將軍澳工業邨',
'dest': '蘇屋'},
'795': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '將軍澳工業邨 (經:日出康城)',
'dest': '長沙灣 (海達)'},
'795P': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '將軍澳工業邨',
'dest': '長沙灣 (海達)'},
'795X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '清水灣半島 (經:尚德)',
'dest': '蘇屋 (經:旺角及美孚)'},
'796P': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '日出康城 (經:尚德)',
'dest': '尖沙咀(東)'},
'796R': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'o',
'orig': '香港體育館',
'dest': '日出康城'},
'796S': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '將軍澳站',
'dest': '牛頭角站'},
'796X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '將軍澳工業邨／將軍澳站',
'dest': '尖沙咀 (東)'},
'797': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '日出康城／將軍澳工業邨',
'dest': '新蒲崗'},
'797M': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '將軍澳站',
'dest': '將軍澳工業邨'},
'798': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '調景嶺站',
'dest': '火炭 (駿洋邨) (經:沙田)'},
'798A': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '將軍澳 (康盛花園)',
'dest': '沙田站'},
'798B': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '日出康城',
'dest': '沙田站'},
'798P': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '將軍澳工業邨',
'dest': '大圍站 (經:沙田)'},
'798X': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '將軍澳工業邨',
'dest': '火炭 (駿洋邨) (經:沙田)'},
'904': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '堅尼地城 (卑路乍灣)',
'dest': '荔枝角'},
'905': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '會展站',
'dest': '荔枝角'},
'905A': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '會展站',
'dest': '荔枝角'},
'905P': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '荔枝角',
'dest': '灣仔 (港灣道)'},
'907B': {'company': 'CTB',
'theme': '#009140',
'mode': 'o',
'orig': '大埔 (廣福球場)',
'dest': '灣仔 (會議展覽中心)'},
'907C': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '大埔頭',
'dest': '灣仔 (會議展覽中心)'},
'914': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '天后站',
'dest': '海麗邨'},
'914P': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '海麗邨',
'dest': '天后站'},
'914X': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '海麗邨',
'dest': '天后站'},
'930': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '荃灣 (愉景新城／荃灣西站)',
'dest': '會展站'},
'930A': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '荃灣西站',
'dest': '會展站'},
'930B': {'company': 'CTB',
'theme': '#009140',
'mode': 'o',
'orig': '葵盛 (東)',
'dest': '銅鑼灣 (摩頓台)'},
'930X': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '荃灣 (愉景新城)',
'dest': '銅鑼灣 (摩頓台)'},
'933': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '荃灣西站',
'dest': '西灣河'},
'948': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '青衣 (長安邨)',
'dest': '天后站'},
'948A': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '長安邨',
'dest': '天后站'},
'948B': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '青衣 (翠怡花園)',
'dest': '天后站'},
'948E': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '青衣站',
'dest': '太古 (康怡廣場)'},
'948P': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '長安邨',
'dest': '天后站'},
'948X': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '長宏邨',
'dest': '天后站'},
'950': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '屯門 (菁田及和田)',
'dest': '會展站'},
'952': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '屯門 (置樂花園)',
'dest': '銅鑼灣 (摩頓台)／金鐘 (西)'},
'952C': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '掃管笏',
'dest': '太古 (康怡廣場)'},
'952P': {'company': 'CTB',
'theme': '#009140',
'mode': 'o',
'orig': '屯門 (置樂花園)',
'dest': '銅鑼灣 (摩頓台)'},
'955': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '屯門 (菁田及和田)',
'dest': '西灣河'},
'962': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '屯門 (龍門居)',
'dest': '銅鑼灣 (摩頓台)'},
'962A': {'company': 'CTB',
'theme': '#009140',
'mode': 'o',
'orig': '屯門 (悅湖山莊)',
'dest': '金鐘'},
'962C': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '屯門 (龍門居)',
'dest': '太古 (康怡廣場)'},
'962G': {'company': 'CTB',
'theme': '#009140',
'mode': 'o',
'orig': '金鐘 (西)',
'dest': '屯門 (湖景路)'},
'962P': {'company': 'CTB',
'theme': '#009140',
'mode': 'o',
'orig': '屯門 (龍門居)',
'dest': '銅鑼灣 (摩頓台)'},
'962X': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '屯門 (龍門居)',
'dest': '銅鑼灣 (摩頓台)'},
'967': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '天水圍 (天恩邨)',
'dest': '金鐘 (西)'},
'967N': {'company': 'CTB',
'theme': '#001142',
'mode': 'o',
'orig': '銅鑼灣 (摩頓台)',
'dest': '天水圍 (天恩邨)'},
'967X': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '天水圍 (天恩邨)',
'dest': '銅鑼灣 (經天水圍北)'},
'969': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '天水圍市中心',
'dest': '銅鑼灣 (摩頓台)'},
'969A': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '天水圍市中心',
'dest': '金鐘'},
'969B': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '天水圍市中心',
'dest': '灣仔'},
'969C': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '天水圍 (天瑞邨)',
'dest': '太古 (康怡廣場)'},
'969N': {'company': 'CTB',
'theme': '#001142',
'mode': 'o',
'orig': '天水圍市中心',
'dest': '銅鑼灣 (摩頓台)'},
'969P': {'company': 'CTB',
'theme': '#009140',
'mode': 'o',
'orig': '天水圍市中心',
'dest': '銅鑼灣 (摩頓台)'},
'969X': {'company': 'CTB',
'theme': '#009140',
'mode': 'o',
'orig': '天水圍市中心',
'dest': '銅鑼灣 (經天水圍南)'},
'970': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '數碼港',
'dest': '蘇屋邨'},
'970X': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '香港仔',
'dest': '長沙灣 (甘泉街)'},
'971': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '香港仔 (石排灣)',
'dest': '海麗邨'},
'973': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '尖沙咀 (麼地道)',
'dest': '赤柱市場'},
'976': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '落馬洲 (新田)',
'dest': '西灣河'},
'976A': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '落馬洲 (新田)',
'dest': '小西灣 (藍灣半島)'},
'979': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '粉嶺皇后山',
'dest': '中環 (香港站)'},
'980A': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '碩門邨',
'dest': '灣仔'},
'980X': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '馬鞍山 (烏溪沙站)',
'dest': '灣仔'},
'981P': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '馬鞍山 (耀安邨)',
'dest': '灣仔'},
'982C': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '碩門邨',
'dest': '西灣河'},
'982X': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '沙田 (愉翠苑)',
'dest': '灣仔'},
'985': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '沙田 (美田邨)',
'dest': '銅鑼灣'},
'985A': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '沙田 (美田邨)',
'dest': '銅鑼灣'},
'985B': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '田心村',
'dest': '銅鑼灣'},
'986': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '沙田圍',
'dest': '西灣河'},
'988': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '柴灣 (東)',
'dest': '泥涌'},
'989': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '火炭 (駿洋邨)',
'dest': '西灣河'},
'A10': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '鴨脷洲 (利樂街)',
'dest': '機場'},
'A11': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '北角碼頭',
'dest': '機場 (經港珠澳大橋香港口岸)'},
'A12': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '機場'},
'A17': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '深灣',
'dest': '機場 (經港珠澳大橋香港口岸)'},
'A20': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '紅磡站',
'dest': '機場'},
'A21': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '紅磡站',
'dest': '機場 (經港珠澳大橋香港口岸)'},
'A22': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '藍田站',
'dest': '機場 (經港珠澳大橋香港口岸)'},
'A23': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '慈雲山 (北)',
'dest': '機場 (經港珠澳大橋香港口岸)'},
'A26': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '油塘',
'dest': '機場'},
'A26P': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'o',
'orig': '油塘',
'dest': '機場'},
'A29': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '將軍澳 (寶琳)',
'dest': '機場 (經港珠澳大橋香港口岸)'},
'A29P': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '將軍澳站',
'dest': '機場'},
'B3': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '屯門碼頭',
'dest': '深圳灣口岸'},
'B3A': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '山景邨',
'dest': '深圳灣口岸'},
'B3M': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'o',
'orig': '深圳灣口岸',
'dest': '屯門站'},
'B3X': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '屯門市中心',
'dest': '深圳灣口岸'},
'B5': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '港珠澳大橋香港口岸',
'dest': '欣澳站'},
'B7': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '上水(寶運路)',
'dest': '香園圍口岸'},
'B8': {'company': 'CTB',
'theme': '#FF0000',
'mode': 'io',
'orig': '大圍站',
'dest': '香園圍口岸'},
'E11': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '天后站',
'dest': '機場博覽館'},
'E11A': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '天后站',
'dest': '機場博覽館 (經東涌北)'},
'E11B': {'company': 'CTB',
'theme': '#009140',
'mode': 'io',
'orig': '天后站',
'dest': '東涌 (滿東邨)'},
'E11S': {'company': 'CTB',
'theme': '#009140',
'mode': 'o',
'orig': '東涌 (滿東邨)',
'dest': '天后站'},
'E21': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '大角咀 (維港灣)',
'dest': '機場博覽館'},
'E21A': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '何文田 (愛民邨)',
'dest': '東涌 (逸東邨)'},
'E21B': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '何文田 (愛民邨)',
'dest': '東涌 (逸東邨)'},
'E21C': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '大角咀 (維港灣)',
'dest': '飛機維修區'},
'E21D': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '大角咀 (維港灣)',
'dest': '機場博覽館 (經:東涌北)'},
'E21X': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'o',
'orig': '東涌 (滿東邨)',
'dest': '紅磡站'},
'E22': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '藍田 (北)',
'dest': '機場博覽館'},
'E22A': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '將軍澳 (康盛花園)',
'dest': '機場博覽館'},
'E22C': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '調景嶺站',
'dest': '飛機維修區'},
'E22P': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '油塘',
'dest': '機場博覽館'},
'E22S': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '東涌 (滿東邨)',
'dest': '將軍澳 (寶琳)'},
'E22X': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '油塘',
'dest': '機場博覽館'},
'E23': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '慈雲山 (南)',
'dest': '機場 (地面運輸中心)'},
'E23A': {'company': 'CTB',
'theme': '#D9261C',
'mode': 'io',
'orig': '慈雲山 (南)',
'dest': '機場 (經東涌北)'},
'H1': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '中環 (天星碼頭)',
'dest': '尖沙咀'},
'H1W': {'company': 'NWFB',
'theme': '#009140',
'mode': 'io',
'orig': '中環 (天星碼頭)',
'dest': '旺角 (染布房街)'},
'H2': {'company': 'NWFB',
'theme': '#ED6D00',
'mode': 'i',
'orig': '中環 (天星碼頭)',
'dest': '尖沙咀'},
'N8': {'company': 'NWFB',
'theme': '#000000',
'mode': 'io',
'orig': '會展站',
'dest': '杏花邨'},
'N8P': {'company': 'NWFB',
'theme': '#000000',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '灣仔 (港灣道)'},
'N8X': {'company': 'CTB',
'theme': '#001142',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '堅尼地城'},
'N11': {'company': 'CTB',
'theme': '#291466',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '機場 (地面運輸中心)'},
'N20': {'company': 'CTB',
'theme': '#001142',
'mode': 'o',
'orig': '大角咀 (維港灣)',
'dest': '啟德 (沐安街)'},
'N21': {'company': 'CTB',
'theme': '#291466',
'mode': 'io',
'orig': '尖沙咀 (天星碼頭)',
'dest': '機場 (地面運輸中心)'},
'N21A': {'company': 'CTB',
'theme': '#291466',
'mode': 'io',
'orig': '尖沙咀 (天星碼頭)',
'dest': '機場 (經逸東邨)'},
'N23': {'company': 'CTB',
'theme': '#291466',
'mode': 'io',
'orig': '慈雲山 (北)',
'dest': '東涌站'},
'N26': {'company': 'CTB',
'theme': '#291466',
'mode': 'io',
'orig': '油塘',
'dest': '東涌站'},
'N29': {'company': 'CTB',
'theme': '#291466',
'mode': 'io',
'orig': '將軍澳 (康盛花園)',
'dest': '東涌站'},
'N72': {'company': 'CTB',
'theme': '#001142',
'mode': 'io',
'orig': '華貴邨',
'dest': '鰂魚涌 (海澤街)'},
'N90': {'company': 'CTB',
'theme': '#001142',
'mode': 'io',
'orig': '海怡半島',
'dest': '中環 (港澳碼頭)'},
'N118': {'company': 'CTB',
'theme': '#000000',
'mode': 'io',
'orig': '小西灣 (藍灣半島)',
'dest': '長沙灣 (深旺道)'},
'N121': {'company': 'NWFB',
'theme': '#000000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '牛頭角'},
'N122': {'company': 'NWFB',
'theme': '#000000',
'mode': 'io',
'orig': '筲箕灣',
'dest': '美孚'},
'N170': {'company': 'CTB',
'theme': '#000000',
'mode': 'io',
'orig': '華富 (中)',
'dest': '沙田巿中心'},
'N171': {'company': 'CTB',
'theme': '#000000',
'mode': 'io',
'orig': '鴨脷洲邨',
'dest': '荔枝角'},
'N182': {'company': 'CTB',
'theme': '#000000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '沙田 (廣源)'},
'N307': {'company': 'CTB',
'theme': '#000000',
'mode': 'io',
'orig': '上環',
'dest': '大埔中心'},
'N619': {'company': 'CTB',
'theme': '#000000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '順利邨'},
'N680': {'company': 'NWFB',
'theme': '#000000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '馬鞍山 (錦英苑)'},
'N691': {'company': 'NWFB',
'theme': '#000000',
'mode': 'io',
'orig': '中環 (港澳碼頭)',
'dest': '調景嶺 (景嶺路)'},
'N796': {'company': 'NWFB',
'theme': '#000000',
'mode': 'io',
'orig': '日出康城',
'dest': '旺角 (經尖沙咀)'},
'N930': {'company': 'CTB',
'theme': '#001142',
'mode': 'io',
'orig': '荃灣 (愉景新城)',
'dest': '銅鑼灣 (摩頓台)'},
'N952': {'company': 'CTB',
'theme': '#001142',
'mode': 'io',
'orig': '屯門 (置樂花園)',
'dest': '銅鑼灣 (摩頓台)'},
'N962': {'company': 'CTB',
'theme': '#001142',
'mode': 'io',
'orig': '屯門 (龍門居)',
'dest': '銅鑼灣 (摩頓台)'},
'N969': {'company': 'CTB',
'theme': '#001142',
'mode': 'io',
'orig': '天水圍市中心',
'dest': '銅鑼灣 (摩頓台)'},
'NA10': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '鴨脷洲 (利樂街)',
'dest': '機場 / 港珠澳大橋香港口岸'},
'NA11': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '北角碼頭',
'dest': '機場 / 港珠澳大橋香港口岸'},
'NA12': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'o',
'orig': '杏花邨',
'dest': '機場 / 港珠澳大橋香港口岸'},
'NA20': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '黃埔花園',
'dest': '機場 / 港珠澳大橋香港口岸'},
'NA21': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'o',
'orig': '機場 / 港珠澳大橋香港口岸',
'dest': '大角咀 (海輝道)'},
'NA29': {'company': 'CTB',
'theme': '#CC0000',
'mode': 'io',
'orig': '將軍澳 (寶琳)',
'dest': '機場 / 港珠澳大橋香港口岸'},
'R8': {'company': 'CTB',
'theme': '#5E89A8',
'mode': 'o',
'orig': '迪士尼樂園',
'dest': '青嶼幹線巴士轉乘站'},
'S1': {'company': 'CTB',
'theme': '#FF6600',
'mode': 'o',
'orig': '東涌站',
'dest': '機場 (一號客運大樓／博覽館)'},
'S52': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '東涌 (逸東邨)',
'dest': '飛機維修區'},
'S52A': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'io',
'orig': '東涌北',
'dest': '飛機維修區'},
'S52P': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '東涌 (逸東邨)',
'dest': '駿坪路 (亞洲空運中心)'},
'S56': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '東涌站',
'dest': '機場 (一號客運大樓)'},
'X1': {'company': 'CTB',
'theme': '#FF6600',
'mode': 'io',
'orig': '東涌站',
'dest': '機場博覽館'},
'X8': {'company': 'CTB',
'theme': '#0080FF',
'mode': 'o',
'orig': '跑馬地 (上)',
'dest': '小西灣 (藍灣半島)'},
'X9': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'i',
'orig': '中環 (天星碼頭)',
'dest': '石澳'},
'X15': {'company': 'NWFB',
'theme': '#7000CC',
'mode': 'io',
'orig': '中環 (天星碼頭)',
'dest': '山頂'},
'X962': {'company': 'CTB',
'theme': '#009140',
'mode': 'o',
'orig': '金鐘 (西)',
'dest': '屯門 (龍門居)'},
'X970': {'company': 'NWFB',
'theme': '#009140',
'mode': 'o',
'orig': '海怡半島',
'dest': '長沙灣 (甘泉街)'}};
